'use client'

import { useState } from 'react'
import { SECURITY_CONTROLS, type SecurityAssessmentResult } from '@/lib/security-assessment'

interface SecurityReportExportProps {
  result: SecurityAssessmentResult
  scores: Record<string, number>
}

export function SecurityReportExport({ result, scores }: SecurityReportExportProps) {
  const [copied, setCopied] = useState(false)

  const generateMarkdownReport = (): string => {
    const date = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })

    let report = '# Security Assessment Matrix Report\n\n'
    report += `**Date:** ${date}\n\n`
    report += `**Overall Score:** ${result.percentage}/100\n\n`
    report += `**Score Band:** ${result.band.label} (${result.band.min}-${result.band.max})\n\n`
    report += `**Assessment:** ${result.interpretation}\n\n`
    report += `---\n\n`

    report += `## Summary\n\n`
    report += `This platform achieved a security assessment score of **${result.percentage}/100**.\n\n`
    report += `Band interpretation: **${result.band.label}**.\n\n`

    report += `## Control Scores\n\n`
    report += `| Control | Weight | Score (0-5) | Weighted |\n`
    report += `|---------|--------|-------------|----------|\n`

    for (const control of SECURITY_CONTROLS) {
      const score = scores[control.id] ?? 0
      const weightedScore = ((score / 5) * control.weight).toFixed(1)
      report += `| ${control.element} | ${control.weight}% | ${score} | ${weightedScore} |\n`
    }

    report += `\n## Category Breakdown\n\n`
    for (const [category, { score, max }] of Object.entries(result.categoryScores)) {
      const percentage = Math.round((score / max) * 100)
      const label = category.charAt(0).toUpperCase() + category.slice(1).replace('-', ' ')
      report += `- **${label}:** ${percentage}% (${score.toFixed(1)}/${max})\n`
    }

    report += `\n## Priorities\n\n`
    if (result.topRisks.length === 0) {
      report += `No significant risk gaps were identified.\n\n`
    } else {
      for (const risk of result.topRisks.slice(0, 5)) {
        const control = SECURITY_CONTROLS.find((candidate) => candidate.id === risk.controlId)
        if (!control) {
          continue
        }
        report += `- **${control.element}**: potential gain +${risk.weightedGap.toFixed(1)} (gap ${risk.gap}/5)\n`
      }
      report += '\n'
    }

    report += `---\n\n`
    report += `*Generated by Digital Platform Architect - Security Assessment Matrix*\n`

    return report
  }

  const handleCopyToClipboard = async () => {
    const report = generateMarkdownReport()
    await navigator.clipboard.writeText(report)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownloadMarkdown = () => {
    const report = generateMarkdownReport()
    const blob = new Blob([report], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `security-assessment-report-${new Date().toISOString().split('T')[0]}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <section className="rounded-xl border border-slate-200 bg-white p-5 sm:p-6">
      <h3 className="text-base font-bold text-slate-900">Export report</h3>
      <p className="mt-2 text-sm text-slate-600">Download or copy this assessment for security reviews and audit documentation.</p>

      <div className="mt-4 flex flex-wrap gap-2">
        <button
          onClick={handleDownloadMarkdown}
          className="inline-flex items-center gap-2 rounded-md bg-blue-600 px-3 py-2 text-sm font-medium text-white transition hover:bg-blue-700"
        >
          <svg className="w-5 h-5" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Download Markdown
        </button>

        <button
          onClick={handleCopyToClipboard}
          className="inline-flex items-center gap-2 rounded-md border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-100"
        >
          <svg className="w-5 h-5" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
          </svg>
          {copied ? 'Copied!' : 'Copy to Clipboard'}
        </button>
      </div>

      <details className="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-3">
        <summary className="cursor-pointer text-sm font-medium text-slate-700">Preview</summary>
        <div className="mt-3 max-h-72 overflow-y-auto rounded-md border border-slate-200 bg-white p-3">
          <pre className="whitespace-pre-wrap text-xs text-slate-700">
            {generateMarkdownReport()}
          </pre>
        </div>
      </details>
    </section>
  )
}
