import type { PersonalizationCatalogItem } from '@/lib/personalization/types'
import type { PersonalizationSurfaceId } from '@/lib/profile/types'

export const PERSONALIZATION_CATALOG: PersonalizationCatalogItem[] = [
  {
    id: 'home-architecture-playground',
    surface: 'home',
    title: 'Interactive Architecture Playground',
    description: 'Explore architecture by persona and detail level with context-aware visuals.',
    href: '/architecture-playground',
    type: 'playground',
    roles: ['ea', 'security', 'data', 'implementation', 'ba'],
    goals: ['design-system', 'evaluate-architecture', 'hands-on-practice', 'validate-design'],
    priority: 100,
    requiresSession: false,
    progressHints: {
      stage: 'early',
      maxCompletedLessons: 8,
    },
  },
  {
    id: 'home-production-readiness',
    surface: 'home',
    title: 'Production Readiness Hub',
    description: 'Run a guided readiness workflow and track critical deployment steps.',
    href: '/playgrounds/production-readiness',
    type: 'assessment',
    roles: ['ea', 'implementation', 'qa', 'security'],
    goals: ['assess-readiness', 'security-review', 'performance-optimization'],
    priority: 95,
    requiresSession: false,
    progressHints: {
      stage: 'mid',
      minCompletedLessons: 3,
    },
  },
  {
    id: 'home-capacity-planning',
    surface: 'home',
    title: 'Capacity Planning Calculator',
    description: 'Estimate scaling targets and infrastructure footprint early.',
    href: '/playgrounds/capacity-planning',
    type: 'playground',
    roles: ['implementation', 'ea', 'data', 'product'],
    goals: ['performance-optimization', 'cloud-migration', 'assess-readiness'],
    priority: 85,
    requiresSession: false,
  },
  {
    id: 'home-patterns-library',
    surface: 'home',
    title: 'Patterns Library',
    description: 'Review architecture patterns and trade-offs before implementation.',
    href: '/patterns',
    type: 'resource',
    roles: [],
    goals: ['learn-patterns', 'understand-trade-offs', 'design-system'],
    priority: 70,
    requiresSession: false,
    progressHints: {
      stage: 'early',
      maxCompletedLessons: 5,
    },
  },
  {
    id: 'home-progress-hub',
    surface: 'home',
    title: 'Progress Hub',
    description: 'Track milestone-based architecture learning progress from real usage.',
    href: '/progress',
    type: 'workflow',
    roles: [],
    goals: ['hands-on-practice', 'build-roadmap'],
    priority: 65,
    requiresSession: true,
    progressHints: {
      stage: 'mid',
      minCompletedLessons: 2,
    },
  },
  {
    id: 'home-file-vault',
    surface: 'home',
    title: 'Secure File Vault',
    description: 'Store architecture notes, docs, and visual artifacts in your private vault.',
    href: '/vault',
    type: 'resource',
    roles: ['ea', 'ba', 'implementation', 'security'],
    goals: ['create-documentation', 'build-roadmap'],
    priority: 55,
    requiresSession: true,
  },
  {
    id: 'playgrounds-architecture-docs',
    surface: 'playgrounds',
    title: 'Architecture Documentation Explorer',
    description: 'View architecture through business, solution, and deployment documentation lenses.',
    href: '/playgrounds/architecture-docs',
    type: 'playground',
    roles: ['business', 'product', 'ba', 'ea'],
    goals: ['create-documentation', 'design-system', 'build-roadmap'],
    priority: 95,
    requiresSession: false,
  },
  {
    id: 'playgrounds-capacity-planning',
    surface: 'playgrounds',
    title: 'Capacity Planning Calculator',
    description: 'Model growth scenarios and baseline infrastructure requirements.',
    href: '/playgrounds/capacity-planning',
    type: 'playground',
    roles: ['implementation', 'ea', 'data', 'product'],
    goals: ['performance-optimization', 'assess-readiness', 'cloud-migration'],
    priority: 90,
    requiresSession: false,
  },
  {
    id: 'playgrounds-operational-sympathy',
    surface: 'playgrounds',
    title: 'Operational Sympathy Scorecard',
    description: 'Assess operational readiness and prioritize production risk mitigations.',
    href: '/playgrounds/operational-sympathy',
    type: 'assessment',
    roles: ['ea', 'implementation', 'qa', 'security'],
    goals: ['assess-readiness', 'evaluate-architecture', 'performance-optimization'],
    priority: 89,
    requiresSession: false,
  },
  {
    id: 'playgrounds-data-pipeline',
    surface: 'playgrounds',
    title: 'Data Pipeline Choreography',
    description: 'Model source-to-insight pipelines and data operating flows.',
    href: '/playgrounds/data-pipeline',
    type: 'playground',
    roles: ['data', 'ea', 'implementation', 'ba'],
    goals: ['data-strategy', 'integration-design', 'explore-technologies'],
    priority: 88,
    requiresSession: false,
  },
  {
    id: 'playgrounds-message-flow',
    surface: 'playgrounds',
    title: 'Message Flow Animation',
    description: 'Visualize sync vs async communication patterns between services.',
    href: '/playgrounds/message-flow',
    type: 'playground',
    roles: ['implementation', 'ea', 'qa', 'security'],
    goals: ['integration-design', 'validate-design', 'understand-trade-offs'],
    priority: 86,
    requiresSession: false,
  },
  {
    id: 'playgrounds-enterprise-integration',
    surface: 'playgrounds',
    title: 'Enterprise Integration',
    description: 'Explore transformation and routing strategies for heterogeneous systems.',
    href: '/playgrounds/enterprise-integration',
    type: 'playground',
    roles: ['ea', 'ba', 'implementation', 'data'],
    goals: ['integration-design', 'cloud-migration', 'build-roadmap'],
    priority: 84,
    requiresSession: false,
  },
  {
    id: 'architecture-default-persona',
    surface: 'architecture-playground',
    title: 'Architecture Playground Persona View',
    description: 'Start from the persona view that matches your current context.',
    href: '/architecture-playground',
    type: 'workflow',
    roles: ['business', 'product', 'ba', 'uxdesigner', 'ea', 'security', 'data', 'implementation', 'qa'],
    goals: ['design-system', 'evaluate-architecture', 'validate-design'],
    priority: 100,
    requiresSession: false,
    progressHints: {
      stage: 'early',
      maxCompletedLessons: 10,
    },
  },
  {
    id: 'architecture-docs-followup',
    surface: 'architecture-playground',
    title: 'Validate with Documentation Explorer',
    description: 'Cross-check the same architecture decisions in formal documentation views.',
    href: '/playgrounds/architecture-docs',
    type: 'resource',
    roles: ['ba', 'ea', 'business', 'product'],
    goals: ['create-documentation', 'build-roadmap', 'design-system'],
    priority: 82,
    requiresSession: false,
  },
  {
    id: 'architecture-patterns-followup',
    surface: 'architecture-playground',
    title: 'Review Pattern Trade-offs',
    description: 'Pair your visual design choices with pattern rationale and trade-offs.',
    href: '/patterns',
    type: 'resource',
    roles: [],
    goals: ['learn-patterns', 'understand-trade-offs', 'validate-design'],
    priority: 78,
    requiresSession: false,
  },
  {
    id: 'production-readiness-operational-sympathy',
    surface: 'production-readiness',
    title: 'Operational Sympathy Assessment',
    description: 'Start by assessing your architecture against operational readiness principles.',
    href: '/playgrounds/operational-sympathy',
    type: 'assessment',
    roles: ['ea', 'implementation', 'qa', 'security'],
    goals: ['assess-readiness', 'evaluate-architecture', 'performance-optimization'],
    priority: 100,
    requiresSession: false,
    progressHints: {
      stage: 'early',
      maxCompletedLessons: 4,
    },
  },
  {
    id: 'production-readiness-capacity-planning',
    surface: 'production-readiness',
    title: 'Infrastructure Capacity Planning',
    description: 'Estimate load envelopes and right-size your deployment footprint.',
    href: '/capacity-planning',
    type: 'assessment',
    roles: ['implementation', 'ea', 'data'],
    goals: ['assess-readiness', 'performance-optimization', 'cloud-migration'],
    priority: 92,
    requiresSession: false,
  },
  {
    id: 'production-readiness-hub',
    surface: 'production-readiness',
    title: 'Continue Readiness Workflow',
    description: 'Use the hub to continue your checklist and export your report.',
    href: '/playgrounds/production-readiness',
    type: 'workflow',
    roles: ['ea', 'implementation', 'security', 'qa'],
    goals: ['assess-readiness', 'build-roadmap', 'security-review'],
    priority: 85,
    requiresSession: false,
    progressHints: {
      stage: 'mid',
      minCompletedLessons: 2,
    },
  },
  {
    id: 'production-readiness-security-reference',
    surface: 'production-readiness',
    title: 'Reference Security Patterns',
    description: 'Review design guidance before finalizing security controls.',
    href: '/patterns',
    type: 'resource',
    roles: ['security', 'ea', 'implementation'],
    goals: ['security-review', 'validate-design'],
    priority: 72,
    requiresSession: false,
  },
]

export function getCatalogForSurface(surface: PersonalizationSurfaceId): PersonalizationCatalogItem[] {
  return PERSONALIZATION_CATALOG.filter((item) => item.surface === surface)
}
