'use client'

import { useState } from 'react'
import { CHECKLIST_ITEMS, type ChecklistScore, type ChecklistResult } from '@/lib/operational-sympathy'

interface ReportExportProps {
  result: ChecklistResult
  scores: ChecklistScore[]
}

export function ReportExport({ result, scores }: ReportExportProps) {
  const [copied, setCopied] = useState(false)

  const generateMarkdownReport = (): string => {
    const scoreMap = new Map(scores.map(s => [s.itemId, s.score]))
    const date = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })

    let report = `# Operational Sympathy Assessment Report\n\n`
    report += `**Date:** ${date}\n\n`
    report += `**Overall Score:** ${result.percentage}/100\n\n`
    report += `**Assessment:** ${result.interpretation}\n\n`
    report += `---\n\n`

    report += `## Summary\n\n`
    report += `This architecture achieved an operational sympathy score of **${result.percentage}/100**, `
    report += `indicating it is **${result.percentage >= 75 ? 'production-ready' : result.percentage >= 60 ? 'approaching production readiness' : 'not yet production-ready'}**.\n\n`

    report += `## Element Scores\n\n`
    report += `| Element | Score | Weighted | Weight | Status |\n`
    report += `|---------|-------|----------|--------|--------|\n`

    CHECKLIST_ITEMS.forEach(item => {
      const score = scoreMap.get(item.id) ?? 0
      const weightedScore = ((score / 5) * item.weight).toFixed(1)
      const status = score >= 4 ? '✅ Strong' : score >= 3 ? '👍 Good' : score >= 2 ? '⚠️ Needs Work' : '❌ Critical'
      report += `| ${item.element} | ${score}/5 | ${weightedScore} | ${item.weight}% | ${status} |\n`
    })

    report += `\n## Category Breakdown\n\n`
    Object.entries(result.categoryScores).forEach(([category, { score, max }]) => {
      const percentage = Math.round((score / max) * 100)
      report += `- **${category.charAt(0).toUpperCase() + category.slice(1)}:** ${percentage}% (${score.toFixed(1)}/${max})\n`
    })

    report += `\n## Recommendations\n\n`

    // Find weak areas
    const weakItems = CHECKLIST_ITEMS.filter(item => {
      const score = scoreMap.get(item.id) ?? 0
      return score < 3
    })

    if (weakItems.length === 0) {
      report += `This architecture demonstrates strong operational sympathy across all elements. Continue monitoring and improving as the system evolves.\n\n`
    } else {
      report += `### Priority Improvements\n\n`
      weakItems.forEach(item => {
        const score = scoreMap.get(item.id) ?? 0
        report += `**${item.element}** (Current: ${score}/5, Weight: ${item.weight}%)\n`
        report += `- ${item.guidance}\n`
        report += `- Priority: ${item.weight >= 15 ? 'High' : item.weight >= 10 ? 'Medium' : 'Low'}\n\n`
      })
    }

    report += `---\n\n`
    report += `*Generated by Digital Platform Architect - Operational Sympathy Checklist*\n`

    return report
  }

  const handleCopyToClipboard = async () => {
    const report = generateMarkdownReport()
    await navigator.clipboard.writeText(report)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownloadMarkdown = () => {
    const report = generateMarkdownReport()
    const blob = new Blob([report], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `operational-sympathy-report-${new Date().toISOString().split('T')[0]}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="bg-white rounded-lg shadow-sm border border-slate-200 p-6">
      <h3 className="text-lg font-bold text-slate-900 mb-4">Export Assessment Report</h3>
      <p className="text-sm text-slate-600 mb-6">
        Download or copy your operational sympathy assessment to share with your team or include in architecture documentation.
      </p>

      <div className="flex flex-wrap gap-3">
        <button
          onClick={handleDownloadMarkdown}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 transition flex items-center gap-2"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Download Markdown
        </button>

        <button
          onClick={handleCopyToClipboard}
          className="px-4 py-2 bg-slate-100 text-slate-700 rounded-lg font-medium hover:bg-slate-200 transition flex items-center gap-2"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
          </svg>
          {copied ? 'Copied!' : 'Copy to Clipboard'}
        </button>
      </div>

      {/* Preview */}
      <details className="mt-6">
        <summary className="cursor-pointer text-sm font-medium text-slate-700 hover:text-slate-900">
          Preview Report
        </summary>
        <div className="mt-4 bg-slate-50 rounded-lg p-4 border border-slate-200 max-h-96 overflow-y-auto">
          <pre className="text-xs text-slate-700 whitespace-pre-wrap font-mono">
            {generateMarkdownReport()}
          </pre>
        </div>
      </details>
    </div>
  )
}
